on:
  workflow_call:
    inputs:
      CMD_FIND_CPP:
        type: string
        default: $(find . \( -iname '*.cpp' \) -print)
      CMD_FIND_HPP:
        type: string
        default: $(find . \( -iname '*.hpp' \) -print)
jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: clang-format check
        run: clang-format-14 --dry-run -Werror ${{inputs.CMD_FIND_CPP}} ${{inputs.CMD_FIND_HPP}}
